name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: github.event_name == 'push'
      - name: Checkout
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Export Environment Variables
        uses: ./.github/actions/vars
        id: vars
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Requirements
        run: |
          pip3 install -r requirements.txt
      - name: Run tests and generate a coverage file
        run: |
          python3 -m pytest --cache-clear --cov=. > pytest-coverage.txt
          echo ${{ steps.vars.outputs.modified-py-files }} > modified-files.txt
          echo check results
          cat pytest-coverage.txt
          cat modified-files.txt
#          grep -f modified-files.txt pytest-coverage.txt > cov_result.txt
      - name: Set the value
        id: step_one
        run: |
          echo 'COVERAGE<<EOF' >> $GITHUB_ENV
          cat cov_result.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Print changed files
        run: |
          echo ${{ steps.vars.outputs.modified-py-files }}
          echo "::set-output name=changed_files::${{ steps.vars.outputs.modified-py-files }}"
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Pytest covereage results of changed files

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Pytest covereage results of changed files
            ${{ env.COVERAGE }}
          edit-mode: replace
